package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1



/**
 * Butacas generated by hbm2java
 */
public class Butacas  implements java.io.Serializable {


     private Integer butCodigo;
     private Sala salas;
     private String butIdentificador;
     private boolean butEstado;

    public Butacas() {
    }

    public Butacas(Sala salas, String butIdentificador, boolean butEstado) {
       this.salas = salas;
       this.butIdentificador = butIdentificador;
       this.butEstado = butEstado;
    }
   
    public Integer getButCodigo() {
        return this.butCodigo;
    }
    
    public void setButCodigo(Integer butCodigo) {
        this.butCodigo = butCodigo;
    }
    public Sala getSalas() {
        return this.salas;
    }
    
    public void setSalas(Sala salas) {
        this.salas = salas;
    }
    public String getButIdentificador() {
        return this.butIdentificador;
    }
    
    public void setButIdentificador(String butIdentificador) {
        this.butIdentificador = butIdentificador;
    }
    public boolean isButEstado() {
        return this.butEstado;
    }
    
    public void setButEstado(boolean butEstado) {
        this.butEstado = butEstado;
    }




}


