package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ButacasCarteleras generated by hbm2java
 */
public class ButacasCarteleras  implements java.io.Serializable {


     private Integer bcCodigo;
     private Carteleras carteleras;
     private String bcIdentificadorButaca;
     private boolean bcDisponible;
     private boolean bcEstado;
     private Set ventasEntradases = new HashSet(0);

    public ButacasCarteleras() {
    }

	
    public ButacasCarteleras(Carteleras carteleras, String bcIdentificadorButaca, boolean bcDisponible, boolean bcEstado) {
        this.carteleras = carteleras;
        this.bcIdentificadorButaca = bcIdentificadorButaca;
        this.bcDisponible = bcDisponible;
        this.bcEstado = bcEstado;
    }
    public ButacasCarteleras(Carteleras carteleras, String bcIdentificadorButaca, boolean bcDisponible, boolean bcEstado, Set ventasEntradases) {
       this.carteleras = carteleras;
       this.bcIdentificadorButaca = bcIdentificadorButaca;
       this.bcDisponible = bcDisponible;
       this.bcEstado = bcEstado;
       this.ventasEntradases = ventasEntradases;
    }
   
    public Integer getBcCodigo() {
        return this.bcCodigo;
    }
    
    public void setBcCodigo(Integer bcCodigo) {
        this.bcCodigo = bcCodigo;
    }
    public Carteleras getCarteleras() {
        return this.carteleras;
    }
    
    public void setCarteleras(Carteleras carteleras) {
        this.carteleras = carteleras;
    }
    public String getBcIdentificadorButaca() {
        return this.bcIdentificadorButaca;
    }
    
    public void setBcIdentificadorButaca(String bcIdentificadorButaca) {
        this.bcIdentificadorButaca = bcIdentificadorButaca;
    }
    public boolean isBcDisponible() {
        return this.bcDisponible;
    }
    
    public void setBcDisponible(boolean bcDisponible) {
        this.bcDisponible = bcDisponible;
    }
    public boolean isBcEstado() {
        return this.bcEstado;
    }
    
    public void setBcEstado(boolean bcEstado) {
        this.bcEstado = bcEstado;
    }
    public Set getVentasEntradases() {
        return this.ventasEntradases;
    }
    
    public void setVentasEntradases(Set ventasEntradases) {
        this.ventasEntradases = ventasEntradases;
    }




}


