package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carteleras generated by hbm2java
 */
public class Carteleras  implements java.io.Serializable {


     private Integer carCodigo;
     private Peliculas peliculas;
     private Salas salas;
     private Date carFecha;
     private String carHorario;
     private double carPrecio;
     private boolean carEstado;
     private Set preciosCartelerases = new HashSet(0);
     private Set butacasCartelerases = new HashSet(0);

    public Carteleras() {
    }

	
    public Carteleras(Peliculas peliculas, Salas salas, Date carFecha, String carHorario, double carPrecio, boolean carEstado) {
        this.peliculas = peliculas;
        this.salas = salas;
        this.carFecha = carFecha;
        this.carHorario = carHorario;
        this.carPrecio = carPrecio;
        this.carEstado = carEstado;
    }
    public Carteleras(Peliculas peliculas, Salas salas, Date carFecha, String carHorario, double carPrecio, boolean carEstado, Set preciosCartelerases, Set butacasCartelerases) {
       this.peliculas = peliculas;
       this.salas = salas;
       this.carFecha = carFecha;
       this.carHorario = carHorario;
       this.carPrecio = carPrecio;
       this.carEstado = carEstado;
       this.preciosCartelerases = preciosCartelerases;
       this.butacasCartelerases = butacasCartelerases;
    }
   
    public Integer getCarCodigo() {
        return this.carCodigo;
    }
    
    public void setCarCodigo(Integer carCodigo) {
        this.carCodigo = carCodigo;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public Date getCarFecha() {
        return this.carFecha;
    }
    
    public void setCarFecha(Date carFecha) {
        this.carFecha = carFecha;
    }
    public String getCarHorario() {
        return this.carHorario;
    }
    
    public void setCarHorario(String carHorario) {
        this.carHorario = carHorario;
    }
    public double getCarPrecio() {
        return this.carPrecio;
    }
    
    public void setCarPrecio(double carPrecio) {
        this.carPrecio = carPrecio;
    }
    public boolean isCarEstado() {
        return this.carEstado;
    }
    
    public void setCarEstado(boolean carEstado) {
        this.carEstado = carEstado;
    }
    public Set getPreciosCartelerases() {
        return this.preciosCartelerases;
    }
    
    public void setPreciosCartelerases(Set preciosCartelerases) {
        this.preciosCartelerases = preciosCartelerases;
    }
    public Set getButacasCartelerases() {
        return this.butacasCartelerases;
    }
    
    public void setButacasCartelerases(Set butacasCartelerases) {
        this.butacasCartelerases = butacasCartelerases;
    }




}


