package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Directores generated by hbm2java
 */
public class Directores  implements java.io.Serializable {


     private Integer dirCodigo;
     private String dirApellidos;
     private String dirNombres;
     private boolean dirEstado;
     private Set pelDirs = new HashSet(0);

    public Directores() {
    }

	
    public Directores(String dirApellidos, String dirNombres, boolean dirEstado) {
        this.dirApellidos = dirApellidos;
        this.dirNombres = dirNombres;
        this.dirEstado = dirEstado;
    }
    public Directores(String dirApellidos, String dirNombres, boolean dirEstado, Set pelDirs) {
       this.dirApellidos = dirApellidos;
       this.dirNombres = dirNombres;
       this.dirEstado = dirEstado;
       this.pelDirs = pelDirs;
    }
   
    public Integer getDirCodigo() {
        return this.dirCodigo;
    }
    
    public void setDirCodigo(Integer dirCodigo) {
        this.dirCodigo = dirCodigo;
    }
    public String getDirApellidos() {
        return this.dirApellidos;
    }
    
    public void setDirApellidos(String dirApellidos) {
        this.dirApellidos = dirApellidos;
    }
    public String getDirNombres() {
        return this.dirNombres;
    }
    
    public void setDirNombres(String dirNombres) {
        this.dirNombres = dirNombres;
    }
    public boolean isDirEstado() {
        return this.dirEstado;
    }
    
    public void setDirEstado(boolean dirEstado) {
        this.dirEstado = dirEstado;
    }
    public Set getPelDirs() {
        return this.pelDirs;
    }
    
    public void setPelDirs(Set pelDirs) {
        this.pelDirs = pelDirs;
    }




}


