package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1



/**
 * PelDir generated by hbm2java
 */
public class PelDir  implements java.io.Serializable {


     private Integer pdCodigo;
     private Directores directores;
     private Pelicula peliculas;
     private boolean pdEstado;

    public PelDir() {
    }

    public PelDir(Directores directores, Pelicula peliculas, boolean pdEstado) {
       this.directores = directores;
       this.peliculas = peliculas;
       this.pdEstado = pdEstado;
    }
   
    public Integer getPdCodigo() {
        return this.pdCodigo;
    }
    
    public void setPdCodigo(Integer pdCodigo) {
        this.pdCodigo = pdCodigo;
    }
    public Directores getDirectores() {
        return this.directores;
    }
    
    public void setDirectores(Directores directores) {
        this.directores = directores;
    }
    public Pelicula getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Pelicula peliculas) {
        this.peliculas = peliculas;
    }
    public boolean isPdEstado() {
        return this.pdEstado;
    }
    
    public void setPdEstado(boolean pdEstado) {
        this.pdEstado = pdEstado;
    }




}


