package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas  implements java.io.Serializable {


     private Integer pelCodigo;
     private String pelNombre;
     private String pelDescripcion;
     private boolean pelEstado;
     private Set pelDirs = new HashSet(0);
     private Set cartelerases = new HashSet(0);
     private Set pelClas = new HashSet(0);

    public Peliculas() {
    }

	
    public Peliculas(String pelNombre, String pelDescripcion, boolean pelEstado) {
        this.pelNombre = pelNombre;
        this.pelDescripcion = pelDescripcion;
        this.pelEstado = pelEstado;
    }
    public Peliculas(String pelNombre, String pelDescripcion, boolean pelEstado, Set pelDirs, Set cartelerases, Set pelClas) {
       this.pelNombre = pelNombre;
       this.pelDescripcion = pelDescripcion;
       this.pelEstado = pelEstado;
       this.pelDirs = pelDirs;
       this.cartelerases = cartelerases;
       this.pelClas = pelClas;
    }
   
    public Integer getPelCodigo() {
        return this.pelCodigo;
    }
    
    public void setPelCodigo(Integer pelCodigo) {
        this.pelCodigo = pelCodigo;
    }
    public String getPelNombre() {
        return this.pelNombre;
    }
    
    public void setPelNombre(String pelNombre) {
        this.pelNombre = pelNombre;
    }
    public String getPelDescripcion() {
        return this.pelDescripcion;
    }
    
    public void setPelDescripcion(String pelDescripcion) {
        this.pelDescripcion = pelDescripcion;
    }
    public boolean isPelEstado() {
        return this.pelEstado;
    }
    
    public void setPelEstado(boolean pelEstado) {
        this.pelEstado = pelEstado;
    }
    public Set getPelDirs() {
        return this.pelDirs;
    }
    
    public void setPelDirs(Set pelDirs) {
        this.pelDirs = pelDirs;
    }
    public Set getCartelerases() {
        return this.cartelerases;
    }
    
    public void setCartelerases(Set cartelerases) {
        this.cartelerases = cartelerases;
    }
    public Set getPelClas() {
        return this.pelClas;
    }
    
    public void setPelClas(Set pelClas) {
        this.pelClas = pelClas;
    }




}


