package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1



/**
 * PreciosCarteleras generated by hbm2java
 */
public class PreciosCarteleras  implements java.io.Serializable {


     private Integer preCodigo;
     private Carteleras carteleras;
     private String preDescripcion;
     private double prePrecio;

    public PreciosCarteleras() {
    }

    public PreciosCarteleras(Carteleras carteleras, String preDescripcion, double prePrecio) {
       this.carteleras = carteleras;
       this.preDescripcion = preDescripcion;
       this.prePrecio = prePrecio;
    }
   
    public Integer getPreCodigo() {
        return this.preCodigo;
    }
    
    public void setPreCodigo(Integer preCodigo) {
        this.preCodigo = preCodigo;
    }
    public Carteleras getCarteleras() {
        return this.carteleras;
    }
    
    public void setCarteleras(Carteleras carteleras) {
        this.carteleras = carteleras;
    }
    public String getPreDescripcion() {
        return this.preDescripcion;
    }
    
    public void setPreDescripcion(String preDescripcion) {
        this.preDescripcion = preDescripcion;
    }
    public double getPrePrecio() {
        return this.prePrecio;
    }
    
    public void setPrePrecio(double prePrecio) {
        this.prePrecio = prePrecio;
    }




}


