package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salas generated by hbm2java
 */
public class Salas  implements java.io.Serializable {


     private Integer salCodigo;
     private String salNombre;
     private String salDescripcion;
     private boolean salEstado;
     private Set butacases = new HashSet(0);
     private Set cartelerases = new HashSet(0);

    public Salas() {
    }

	
    public Salas(String salNombre, String salDescripcion, boolean salEstado) {
        this.salNombre = salNombre;
        this.salDescripcion = salDescripcion;
        this.salEstado = salEstado;
    }
    public Salas(String salNombre, String salDescripcion, boolean salEstado, Set butacases, Set cartelerases) {
       this.salNombre = salNombre;
       this.salDescripcion = salDescripcion;
       this.salEstado = salEstado;
       this.butacases = butacases;
       this.cartelerases = cartelerases;
    }
   
    public Integer getSalCodigo() {
        return this.salCodigo;
    }
    
    public void setSalCodigo(Integer salCodigo) {
        this.salCodigo = salCodigo;
    }
    public String getSalNombre() {
        return this.salNombre;
    }
    
    public void setSalNombre(String salNombre) {
        this.salNombre = salNombre;
    }
    public String getSalDescripcion() {
        return this.salDescripcion;
    }
    
    public void setSalDescripcion(String salDescripcion) {
        this.salDescripcion = salDescripcion;
    }
    public boolean isSalEstado() {
        return this.salEstado;
    }
    
    public void setSalEstado(boolean salEstado) {
        this.salEstado = salEstado;
    }
    public Set getButacases() {
        return this.butacases;
    }
    
    public void setButacases(Set butacases) {
        this.butacases = butacases;
    }
    public Set getCartelerases() {
        return this.cartelerases;
    }
    
    public void setCartelerases(Set cartelerases) {
        this.cartelerases = cartelerases;
    }




}


