package aplicacion.datos.hibernate.mapeos;
// Generated 07/06/2018 16:43:58 by Hibernate Tools 4.3.1



/**
 * VentasEntradas generated by hbm2java
 */
public class VentasEntradas  implements java.io.Serializable {


     private Integer venCodigo;
     private ButacasCarteleras butacasCarteleras;
     private Perfiles perfiles;
     private String venPrecio;
     private String venDescripcion;
     private boolean venEstado;

    public VentasEntradas() {
    }

    public VentasEntradas(ButacasCarteleras butacasCarteleras, Perfiles perfiles, String venPrecio, String venDescripcion, boolean venEstado) {
       this.butacasCarteleras = butacasCarteleras;
       this.perfiles = perfiles;
       this.venPrecio = venPrecio;
       this.venDescripcion = venDescripcion;
       this.venEstado = venEstado;
    }
   
    public Integer getVenCodigo() {
        return this.venCodigo;
    }
    
    public void setVenCodigo(Integer venCodigo) {
        this.venCodigo = venCodigo;
    }
    public ButacasCarteleras getButacasCarteleras() {
        return this.butacasCarteleras;
    }
    
    public void setButacasCarteleras(ButacasCarteleras butacasCarteleras) {
        this.butacasCarteleras = butacasCarteleras;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public String getVenPrecio() {
        return this.venPrecio;
    }
    
    public void setVenPrecio(String venPrecio) {
        this.venPrecio = venPrecio;
    }
    public String getVenDescripcion() {
        return this.venDescripcion;
    }
    
    public void setVenDescripcion(String venDescripcion) {
        this.venDescripcion = venDescripcion;
    }
    public boolean isVenEstado() {
        return this.venEstado;
    }
    
    public void setVenEstado(boolean venEstado) {
        this.venEstado = venEstado;
    }




}


